exclude: |
  (?x)^(
      .+/.openapi-generator/.+|
      .+/openapi/openapi.yaml|
      gradlew.*|
      gradle/.+|
      README.md
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.2.0'
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=no ]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [ --allow-multiple-documents ]
      - id: check-json
      - id: check-toml
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.4.0'
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/hadolint/hadolint
    rev: 'v2.10.0'
    hooks:
      - id: hadolint
